# Generated by Django 2.2.6 on 2020-09-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200910_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='sku_id',
        ),
    ]
