# Generated by Django 2.2.6 on 2020-09-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200910_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku_id',
            new_name='sku',
        ),
    ]
